// ---------- Michell's integral: wave resistance and the Kelvin wave pattern ----------
//
// Thin-ship theory replaces the hull by its CENTREPLANE PROJECTION: a half-breadth field f(X, Z) ≥ 0 on the
// vertical plane through the ship's track, zero outside the hull's shadow. Everything below — the wave
// resistance and the far-field wave pattern alike — is generated by one complex function of the wave
// propagation angle θ, the hull's free-wave spectrum
//
//     F(θ) = ∬ ∂f/∂X · exp(ν·sec²θ·Z + i·ν·secθ·X) dX dZ ,        ν = g/U²
//
// with X along the track (the ship advances toward +X, so the wake trails toward −X), Z = 0 the free surface
// and Z ≤ 0 submerged. Resistance is R_w = (4ρg²/πU²)∫₀^{π/2} sec³θ·|F|² dθ; the elevation follows in §4.
//
// ---------- why there is no boundary term ----------
//
// f has compact support (it is the half-breadth INSIDE the hull's shadow and zero outside), so integrating by
// parts in X over the whole centreplane leaves nothing at infinity:
//
//     F(θ) = −i·ν·secθ · ∬_D y · exp(ν·sec²θ·Z + i·ν·secθ·X) dX dZ
//
// where D is the wetted projected domain and y the half-breadth on it. This is worth stating plainly because
// it is easy to get wrong: applying the divergence theorem to the OPEN domain D alone leaves a transom line
// integral ∮ y e^K dZ, and a raked transom makes its measure fiddly. But f also JUMPS from 0 to f_T across the
// transom, and that jump is a delta in ∂f/∂X sitting exactly on the same line — the two cancel identically.
// (Verified on a prismatic test body in test/michell.ts, rung 2.) So a transom hull needs no special term: the
// concentrated transom source line is already in the answer, which is the honest thin-ship treatment of a
// blunt ending — see the caveat in §5.
//
// Only y appears, never a derivative of y: the one derivative in Michell's integral has been moved onto the
// exponential, where it is exact. This is the numerically strongest form available.
//
// ---------- why the integral is taken in camber's own (u, v) ----------
//
// The obvious route is to extract the graph y = f(X, Z) and integrate over a rectangle, which costs a
// root-solve per sample to invert the section's depth. camber never needs that: the hull is already a
// parametric map (u, v) ↦ (x, y, z) — the sheer plan's parameter u along the hull, the section curve's
// parameter v down each station — so the projection integral is a plain change of variables
//
//     ∬_D y·e^K dX dZ = ∬_Ω y(u,v)·e^{K(u,v)}·|J| du dv ,   J = X_u·Z_v − X_v·Z_u
//
// with Ω the wetted (u, v) region. No inversion anywhere, and — the point — camber's station planes FAN as the
// plan turns, so a surface point labelled (u, v) has a true longitudinal coordinate that is not the station's
// x. Codes that integrate station by station must either ignore that or correct for it; here the Jacobian
// carries it EXACTLY, at no cost. It is not a small effect: the longitudinal phase error from ignoring it is
// ν·secθ·δX = (δX/L)·secθ/Fn², which for camber's default hull (δX/L ≈ 1.7%) is order 1 radian at Fn 0.3 near
// the angular cutoff.
//
// ---------- the shape of the computation ----------
//
// The geometry sampling is θ-INDEPENDENT: sampleCenterplane() walks the hull once and reduces it to a cloud of
// nodes (X, Z, W = y·|J|·quadrature weight). Every θ afterwards is one pass over that cloud — and because
// b = i·ν·secθ is purely imaginary whatever the rake (the rake is already inside X and Z), a node costs one
// exp and one sin/cos, never a complex exponential. Resistance and wave pattern read the same cloud.

import {
  bisectRoot,
  bisectWhile,
  frameAt,
  immersion,
  sectionAt,
  stationWorld,
  xTransom,
  type Frame,
  type Model,
  type Section,
} from "./model";

export const G = 9.80665; // m/s², standard gravity
export const RHO_SALT = 1025; // kg/m³
export const RHO_FRESH = 1000;
export const KNOT = 0.514444; // m/s per knot

// ---------- Gauss–Legendre ----------
// Nodes and weights on [−1, 1] by Newton on the Legendre polynomial. Orders here are small and fixed, and the
// result is cached: the same handful of rules is asked for once per column.
const glCache = new Map<number, { x: Float64Array; w: Float64Array }>();
export function gaussLegendre(n: number): { x: Float64Array; w: Float64Array } {
  const hit = glCache.get(n);
  if (hit) return hit;
  const x = new Float64Array(n),
    w = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    let t = Math.cos((Math.PI * (i + 0.75)) / (n + 0.5)),
      dp = 1;
    for (let it = 0; it < 100; it++) {
      let p0 = 1,
        p1 = 0;
      for (let j = 0; j < n; j++) {
        const p2 = p1;
        p1 = p0;
        p0 = ((2 * j + 1) * t * p1 - j * p2) / (j + 1);
      }
      dp = (n * (t * p0 - p1)) / (t * t - 1);
      const dt = -p0 / dp;
      t += dt;
      if (Math.abs(dt) < 1e-15) break;
    }
    x[i] = t;
    w[i] = 2 / ((1 - t * t) * dp * dp);
  }
  const r = { x, w };
  glCache.set(n, r);
  return r;
}

// ---------- 1. sampling the wetted centreplane projection ----------

export interface MichellOptions {
  uPanels: number; // longitudinal panels over the wetted span
  uNodes: number; // Gauss nodes per longitudinal panel (columns = uPanels × uNodes)
  vPanels: number; // uniform sub-panels per section band (see sizeFor: the station fan needs these)
  vNodes: number; // Gauss nodes per section sub-panel
  wlGrade: number; // geometrically graded sub-panels in the topmost section band
  scanV: number; // coarse samples per column when bracketing the wetted span
}

// The BASELINE resolution — the geometry floor, not the answer. It resolves the hull's shape, and at moderate
// Froude number that is all the kernel asks for: measured against a deliberately over-resolved reference
// (225k nodes) on camber's default hull at Fn 0.32, it lands R_w within 0.01% for 7.7k nodes.
//
// It is NOT sufficient on its own. exp(i·ν·secθ·X) oscillates faster and faster as speed drops, and a fixed
// grid silently stops resolving it — at Fn 0.08 this baseline reports 6690 N where the converged answer is
// 191 N. sizeFor() below raises these from the actual bandwidth, and every caller that knows the speed must
// go through it. See the speed sweep in test/michell.ts, which is what would catch this returning.
export const DEFAULT_OPTIONS: MichellOptions = {
  uPanels: 96,
  uNodes: 3,
  vPanels: 1,
  vNodes: 4,
  wlGrade: 5,
  scanV: 64,
};

// The θ-independent reduction of a hull: its wetted centreplane projection as a weighted node cloud, in SI.
export interface Centerplane {
  X: Float64Array; // node position along the track [m], +X toward the bow
  Z: Float64Array; // node depth [m], ≤ 0
  W: Float64Array; // node weight = y·|J|·w_u·w_v [m³] — Σ W is ∬ y dX dZ
  // ---- principal dimensions of the projection, all SI ----
  volumeHalf: number; // ∬ y dX dZ = half the displaced volume under the projection
  areaProjected: number; // ∬ dX dZ, the centreplane area (the "profile" area)
  draft: number; // greatest immersion
  xAft: number; // wetted span in X
  xFwd: number;
  beamMax: number; // greatest half-breadth × 2
  wettedLength: number; // xFwd − xAft
  // ---- diagnostics: every one of these is a way the sampling can be wrong ----
  columns: number;
  nodes: number;
  jacobianFlips: number; // nodes whose Jacobian sign disagrees with the hull's — a folded projection
  sheerSubmerged: number; // columns whose top is cut by the sheer trim, not the waterline (a swamped rail)
  fanMaxRatio: number; // max |δX|/L, the longitudinal offset the station-plane fan introduces
  fanSpread: number; // the same offset in metres — the length scale the section axis must resolve in X
  footU: number | null; // u where the domain's lower edge leaves the transom for the keel, if it does
  spanFallbacks: number; // columns whose bracket came from a scan, not the domain's table (see spanAt)
}

// The surface point at (u, v) in the hydrodynamic frame: X along the track, Z down from the free surface.
// worldZ's rotation with the design waterline folded in, so Z = 0 IS the free surface and Z = −immersion.
interface Hydro2 {
  X: number;
  Z: number;
  y: number;
}
function hydroAt(
  model: Model,
  fr: Frame,
  sec: Section,
  v: number,
  cr: number,
  sr: number,
): Hydro2 {
  const [n, z] = sec.at(v),
    p = stationWorld(fr, n, z);
  return {
    X: p[0] * cr - p[2] * sr,
    Z: p[0] * sr + p[2] * cr + model.waterline,
    y: p[1],
  };
}

// How far inside the WETTED hull a section point is, as one signed number: camber's own three trims (sheer,
// centerline, transom) plus immersion below the design waterline. Taking the min makes "this point is wetted
// hull" a single sign test, so one bisection lands on whichever boundary happens to bind — exactly the
// construction keepAt() uses for the mesh, with the waterline added.
function wetAt(model: Model, fr: Frame, sec: Section, v: number): number {
  const [n, z] = sec.at(v),
    p = stationWorld(fr, n, z);
  return Math.min(
    model.trimZ(p[0]) - p[2], // at or below the sheer trim
    p[1], // at or inboard of the centerline
    p[0] - xTransom(model, p[2]), // forward of the transom
    immersion(model, p[0], p[2]), // at or below the design waterline
  );
}

// which of the four constraints binds at a point: 0 sheer, 1 centerline, 2 transom, 3 waterline
function bindingAt(model: Model, fr: Frame, sec: Section, v: number): number {
  const [n, z] = sec.at(v),
    p = stationWorld(fr, n, z);
  const c = [
    model.trimZ(p[0]) - p[2],
    p[1],
    p[0] - xTransom(model, p[2]),
    immersion(model, p[0], p[2]),
  ];
  let k = 0;
  for (let i = 1; i < 4; i++) if (c[i] < c[k]) k = i;
  return k;
}

// The wetted span of the section at u, as [vTop, vBot], or null where the column is dry or cut away entirely.
// Coarse scan to bracket, then bisection to converge: wetAt is a min of four constraints, so it has kinks
// where the binding constraint changes and a root-finder assuming smoothness could walk off one.
function wetSpan(
  model: Model,
  fr: Frame,
  sec: Section,
  scan: number,
): [number, number] | null {
  const g = (v: number): number => wetAt(model, fr, sec, v);
  const gs: number[] = [];
  for (let i = 0; i <= scan; i++) gs.push(g((sec.vmax * i) / scan));
  let lo = -1,
    hi = -1;
  for (let i = 0; i <= scan; i++)
    if (gs[i] >= 0) {
      if (lo < 0) lo = i;
      hi = i;
    }
  if (lo < 0) return null;
  const at = (i: number): number => (sec.vmax * i) / scan;
  const vTop = lo === 0 ? 0 : bisectRoot(g, at(lo - 1), at(lo), gs[lo - 1]);
  const vBot =
    hi === scan ? sec.vmax : bisectRoot(g, at(hi + 1), at(hi), gs[hi + 1]);
  return vBot > vTop + 1e-12 ? [vTop, vBot] : null;
}

// the deepest the column reaches into the wetted region — the signed function whose root is the fore/aft end
// of the wetted domain. Positive where the hull has any wetted section at u at all.
function columnReach(model: Model, u: number, scan: number): number {
  const fr = frameAt(model, u),
    sec = sectionAt(model, u);
  let m = -Infinity;
  for (let i = 0; i <= scan; i++)
    m = Math.max(m, wetAt(model, fr, sec, (sec.vmax * i) / scan));
  return m;
}

// ---------- 1a. the wetted domain ----------
//
// WHERE the wetted hull is, with no reference to any quadrature grid: the fore and aft limits in u, and — for
// each edge of the section span — which of wetAt's constraints cuts it over which run of u. It depends on the
// model's geometry, trims, waterline and rake and on nothing else. Not on the resolution, and not even on
// `scale`, which enters only when the nodes are converted to SI. So it is built once and handed to every
// sample: the two passes of sampleForBandwidth stop re-deriving the same boundary, and a speed slider that
// crosses a rung of the ladder re-integrates without re-finding the hull.
//
// The run boundaries are the point. wetAt is a min of four constraints, so it is smooth EXCEPT where the
// binding constraint switches — every switch is a C⁰ corner in vTop(u) or vBot(u), and a corner inside a
// longitudinal panel costs that panel's quadrature all of its order, silently. The transom→keel corner on the
// lower edge (the "foot") used to be the only one this code looked for. The upper edge has them too: wherever
// a submerged rail hands the cut back from the sheer to the waterline, vTop kinks exactly as hard.

// What cuts one edge of the section span: an index into wetAt's four constraints (matching bindingAt), or
// `end` where no constraint cuts it at all and the section curve simply runs out while still wet.
export const BOUND = {
  sheer: 0,
  centerline: 1,
  transom: 2,
  waterline: 3,
  end: -1,
} as const;
export type Bound = (typeof BOUND)[keyof typeof BOUND];

// One run of u over which an edge keeps the same bound. The first begins at uA, each ends where the next
// begins, and the last ends at uB.
export interface EdgeRun {
  uTo: number;
  bound: Bound;
}

export interface WettedDomain {
  uA: number; // the fore and aft limits, where the wetted section closes to a point
  uB: number;
  top: EdgeRun[]; // what cuts vTop(u), run by run
  bot: EdgeRun[]; // and vBot(u)
  breaks: number[]; // sorted interior u the longitudinal panels must split on: bound switches and stations
  footU: number | null; // where the lower edge leaves the transom for the keel, if it does
  // Whether every column's wetted set is ONE v-interval, which is what wetSpan's outermost bracket assumes.
  // Checked at the scan columns only, so `true` means "not seen", not "does not happen": `hull-beamy` has a
  // notched section over a band of u 0.0005 wide that this misses entirely, and finding it would cost more
  // than the sampling it informs. spanAt therefore certifies every column itself rather than trusting this.
  singleInterval: boolean;
  scanV: number; // the section scan the runs were labelled with — the labels are only as good as it
  // ---- the edges tabulated across [uA, uB], for BRACKETING and nothing else ----
  // Not the answer, and never used as one. A bisection needs an interval that straddles the crossing and
  // asks nothing else of it — so a coarse table is enough to produce one in O(1) where a scan costs `scanV`
  // evaluations, and the bisection that follows converges to the same 1e-12 however loose the table was.
  // This is the distinction that makes the table safe: interpolating the boundary would move the answer,
  // bracketing it cannot.
  uTab: Float64Array; // NT+1 samples spanning [uA, uB]
  vTopTab: Float64Array; // vTop there, NaN where the column is dry
  vBotTab: Float64Array;
}

// What cuts an edge sitting at v. `limit` is the parameter end this edge can rest on (0 for the top, vmax for
// the bottom): an edge resting there with the hull still wet is cut by nothing, and no root was found for it.
// Reporting a constraint in that case would invent a corner that is not there.
function boundOf(
  model: Model,
  fr: Frame,
  sec: Section,
  v: number,
  limit: number,
): Bound {
  if (Math.abs(v - limit) < 1e-12 && wetAt(model, fr, sec, v) > 0)
    return BOUND.end;
  return bindingAt(model, fr, sec, v) as Bound;
}

// How many separate wet runs the column at u has. wetSpan takes the OUTERMOST bracket, which is the right
// answer only when there is exactly one — a section that dips dry in the middle (a tunnel, a deep notch)
// would be silently filled in. Checked once here rather than assumed at every column.
function wetRunCount(
  model: Model,
  fr: Frame,
  sec: Section,
  scan: number,
): number {
  let runs = 0,
    wasWet = false;
  for (let i = 0; i <= scan; i++) {
    const wet = wetAt(model, fr, sec, (sec.vmax * i) / scan) >= 0;
    if (wet && !wasWet) runs++;
    wasWet = wet;
  }
  return runs;
}

export function wettedDomain(
  model: Model,
  scanV: number = DEFAULT_OPTIONS.scanV,
): WettedDomain | null {
  // ---- the wetted span in u. Bracket by scanning, then converge both ends: at the fore and aft limits the
  // wetted section shrinks to a point, so the domain closes there and no edge term is left over.
  const NSCAN = 96;
  let uLo = -1,
    uHi = -1;
  const reach: number[] = [];
  for (let i = 0; i <= NSCAN; i++) {
    const r = columnReach(model, i / NSCAN, 24);
    reach.push(r);
    if (r >= 0) {
      if (uLo < 0) uLo = i;
      uHi = i;
    }
  }
  if (uLo < 0) return null; // no wetted hull at all
  const rc = (u: number): number => columnReach(model, u, 24);
  const uA =
    uLo === 0
      ? 0
      : bisectRoot(rc, (uLo - 1) / NSCAN, uLo / NSCAN, reach[uLo - 1]);
  const uB =
    uHi === NSCAN
      ? 1
      : bisectRoot(rc, (uHi + 1) / NSCAN, uHi / NSCAN, reach[uHi + 1]);
  if (!(uB > uA)) return null;

  // ---- the edge runs. One scan along the hull reading both edges of every column; wherever an edge changes
  // which constraint cuts it, converge the switch by bisection. What is being bisected is a BOOLEAN ("is this
  // edge still cut by the constraint it was"), not a smooth function with a root, so it is plain halving.
  const NF = 48, // scan columns
    NB = 24, // bisection iterations per switch
    span = uB - uA;
  // the bracket table is filled from this same pass — every sample here already pays for a full wetSpan, so
  // recording where its edges landed costs two stores and saves the sampler a scan per column later
  const uTab = new Float64Array(NF + 1),
    vTopTab = new Float64Array(NF + 1).fill(NaN),
    vBotTab = new Float64Array(NF + 1).fill(NaN);
  // slot 0 sits at the probe just inside uA, not at uA itself, because that is where it was measured
  uTab[0] = uA + span * 1e-4;
  for (let i = 1; i <= NF; i++) uTab[i] = uA + (span * i) / NF;
  const edgesAt = (u: number, tab = -1): [Bound, Bound] | null => {
    const fr = frameAt(model, u),
      sec = sectionAt(model, u),
      sp = wetSpan(model, fr, sec, scanV);
    if (!sp) return null;
    if (tab >= 0) {
      vTopTab[tab] = sp[0];
      vBotTab[tab] = sp[1];
    }
    return [
      boundOf(model, fr, sec, sp[0], 0),
      boundOf(model, fr, sec, sp[1], sec.vmax),
    ];
  };
  const top: EdgeRun[] = [],
    bot: EdgeRun[] = [];
  let singleInterval = true;
  // start just inside uA: at uA itself the section has closed to a point and neither edge means anything
  let prev = edgesAt(uTab[0], 0);
  for (let i = 1; i <= NF; i++) {
    const u = uA + (span * i) / NF;
    const fr = frameAt(model, u),
      sec = sectionAt(model, u);
    if (wetRunCount(model, fr, sec, scanV) > 1) singleInterval = false;
    const cur = edgesAt(u, i);
    if (!cur) continue; // the section has closed (the far end) — nothing to compare
    if (!prev) {
      prev = cur;
      continue;
    }
    for (const e of [0, 1] as const) {
      if (cur[e] === prev[e]) continue;
      const was = prev[e];
      const uTo = bisectWhile(
        (m) => {
          const k = edgesAt(m);
          return !!k && k[e] === was;
        },
        uA + (span * (i - 1)) / NF,
        u,
        NB,
      );
      (e === 0 ? top : bot).push({ uTo, bound: was });
    }
    prev = cur;
  }
  top.push({ uTo: uB, bound: prev ? prev[0] : BOUND.end });
  bot.push({ uTo: uB, bound: prev ? prev[1] : BOUND.end });

  // ---- the panel breaks: every interior corner the u-quadrature must not integrate across. The bound
  // switches above, plus the station knots (the loft is only C¹ across one).
  const breaks = new Set<number>();
  for (const st of model.stations)
    if (st.u > uA + 1e-9 && st.u < uB - 1e-9) breaks.add(st.u);
  for (const r of [...top, ...bot])
    if (r.uTo > uA + 1e-9 && r.uTo < uB - 1e-9) breaks.add(r.uTo);

  // the foot, kept as its own number because it is the one corner with a name and a diagnostic. The trailing
  // run ends at uB and is not a switch, so it cannot supply one.
  const foot = bot.find((r) => r.bound === BOUND.transom && r.uTo < uB);

  return {
    uA,
    uB,
    top,
    bot,
    breaks: [...breaks].sort((a, b) => a - b),
    footU: foot ? foot.uTo : null,
    singleInterval,
    scanV,
    uTab,
    vTopTab,
    vBotTab,
  };
}

// ---------- 1a′. the span search, given the domain ----------
//
// The domain-guided half. Most classification has already been settled by the domain; what remains is to look
// up a bracket, check that the pre-classified route still holds at this exact column, and halve it. Those checks
// and the fallback they may select belong to plan compilation below, never to the numerical evaluator.
//
// The bracket comes from the table, widened by the amount the edge moved between the two samples around u.
// If it straddles, bisection converges to the crossing, because BISECTION DOES NOT CARE what the function
// does inside the bracket — not its smoothness, not the kinks where the binding constraint changes, nothing
// but the two signs at the ends.
//
// ---------- but a bracket is not all the scan was for ----------
//
// wetSpan takes the OUTERMOST wet sample at each end, which does two jobs: it brackets the crossing, and it
// certifies there is no further wet band beyond it. A bracket replaces the first job and not the second, and
// the difference is not academic — `hull-beamy` and `cuvature-kink` both have a narrow band of u (0.0005 and
// 0.0035 wide, near the foot) where the section dips dry and comes back, so the column's wetted set is TWO
// intervals. wetSpan spans the gap; a bracketed search converges on the inner crossing and stops. Neither is
// the true integral over a notched section, but they are different, and a sampler that quietly changed which
// one it computed depending on where a Gauss node happened to land would be indefensible.
//
// So the span is certified after it is found: the scan's own grid points OUTSIDE the span are tested, and any
// wet one sends this to the full scan. That costs ~31 of the 64 samples on camber's hulls rather than 64,
// which is a far smaller win than dropping the scan entirely — and it is the honest price of the guarantee
// that this returns what wetSpan returns.
//
// Fallbacks are counted in `spanFallbacks` rather than hidden, because a hull that takes that path often has
// quietly lost the optimisation.

// Where the crossing is, given an interval known to straddle it: `dry` is the end outside the wetted hull.
// Both edges of the span reduce to this, which is why there is one call and not two shapes.
const convergeEdge = (
  model: Model,
  fr: Frame,
  sec: Section,
  dry: number,
  wet: number,
): number => bisectWhile((v) => wetAt(model, fr, sec, v) < 0, dry, wet);

// The bound of `runs` at u. The runs are few (one per corner) and u ascends through the sampler's columns, so
// a walk from the front costs nothing worth indexing away.
const boundAt = (runs: EdgeRun[], u: number): Bound => {
  for (const r of runs) if (u <= r.uTo) return r.bound;
  return runs[runs.length - 1].bound;
};

type Span = [number, number] | null;
type FastSpan = { resolved: true; span: Span } | { resolved: false };

// The slow, general resolver. It owns the scan and all of the discrete decisions that follow from it.
const resolveSpanByScan = (
  model: Model,
  fr: Frame,
  sec: Section,
  scanV: number,
): Span => wetSpan(model, fr, sec, scanV);

// Try the domain's pre-classified route. Failure here is not a dry column: it means one of the assumptions
// encoded by the domain did not hold at this particular u, and the caller must use resolveSpanByScan.
const resolveSpanFast = (
  model: Model,
  dom: WettedDomain,
  fr: Frame,
  sec: Section,
  u: number,
  scanV: number,
): FastSpan => {
  const n = dom.uTab.length;
  // the table cell containing u; uTab is uniform apart from slot 0, so this lands within one of the true cell
  let i = Math.floor(((u - dom.uA) / (dom.uB - dom.uA)) * (n - 1));
  if (i < 0) i = 0;
  if (i > n - 2) i = n - 2;
  const t0 = dom.vTopTab[i],
    t1 = dom.vTopTab[i + 1],
    b0 = dom.vBotTab[i],
    b1 = dom.vBotTab[i + 1];
  if (!(isFinite(t0) && isFinite(t1) && isFinite(b0) && isFinite(b1)))
    return { resolved: false }; // a dry table sample either side — the ends of the hull

  // pad by the edge's own movement across the cell, plus a floor for where it barely moves at all
  const padT = 0.5 * Math.abs(t1 - t0) + 1e-3 * sec.vmax,
    padB = 0.5 * Math.abs(b1 - b0) + 1e-3 * sec.vmax;
  const tDry = Math.max(0, Math.min(t0, t1) - padT),
    tWet = Math.min(sec.vmax, Math.max(t0, t1) + padT),
    bWet = Math.max(0, Math.min(b0, b1) - padB),
    bDry = Math.min(sec.vmax, Math.max(b0, b1) + padB);

  // the top edge: cut by nothing means it IS the section's start, and there is no crossing to find
  const topEnd = boundAt(dom.top, u) === BOUND.end;
  const botEnd = boundAt(dom.bot, u) === BOUND.end;
  const wetHere = (v: number): boolean => wetAt(model, fr, sec, v) >= 0;
  let vTop: number, vBot: number;
  if (topEnd) {
    if (!wetHere(0)) return { resolved: false }; // the label disagrees with the hull — trust the hull
    vTop = 0;
  } else {
    if (wetHere(tDry) || !wetHere(tWet)) return { resolved: false }; // no straddle
    vTop = convergeEdge(model, fr, sec, tDry, tWet);
  }
  if (botEnd) {
    if (!wetHere(sec.vmax)) return { resolved: false };
    vBot = sec.vmax;
  } else {
    if (wetHere(bDry) || !wetHere(bWet)) return { resolved: false };
    vBot = convergeEdge(model, fr, sec, bDry, bWet);
  }

  // the certification: on wetSpan's own grid, nothing outside this span may be wet. Same grid, so anything
  // the scan would have found here is found here too — that equality is the point, not a near-miss of it.
  for (let j = 0; j <= scanV; j++) {
    const v = (sec.vmax * j) / scanV;
    if (v >= vTop && v <= vBot) continue;
    if (wetHere(v)) return { resolved: false };
  }
  return {
    resolved: true,
    span: vBot > vTop + 1e-12 ? [vTop, vBot] : null,
  };
};

// Public for the domain tests and diagnostics. Production sampling calls this only while compiling its column
// plan; the numerical integration loop never sees the fast/fallback branch or a dry column.
export function spanAt(
  model: Model,
  dom: WettedDomain,
  fr: Frame,
  sec: Section,
  u: number,
  scanV: number,
): { span: Span; fellBack: boolean } {
  const fast = resolveSpanFast(model, dom, fr, sec, u, scanV);
  return fast.resolved
    ? { span: fast.span, fellBack: false }
    : { span: resolveSpanByScan(model, fr, sec, scanV), fellBack: true };
}

// The section sub-panel edges over [vTop, vBot]. Two things break smoothness in v and both become edges:
//
//   • STATION KNOTS. The section is a Catmull-Rom through the lofted station points and a knuckle lives at a
//     knot, so an integer v inside the span is a C⁰ corner. Integrating across one silently costs the
//     quadrature all of its order.
//   • THE WATERLINE. exp(ν·sec²θ·Z) concentrates the integrand into a boundary layer of thickness ~1/(ν sec²θ)
//     below the free surface, which at the angular cutoff is a small fraction of the draft. The topmost band
//     is therefore graded geometrically toward vTop, finest at the surface. The grading is θ-INDEPENDENT (the
//     concentration is always toward the waterline, never away from it), which is what lets the whole node
//     cloud be built once and reused at every θ.
//
// And one thing makes the section direction OSCILLATORY, which is easy to miss: because camber's station
// planes fan, a single column spans a range of X, so exp(i·ν·secθ·X) varies along v as well as along u. Near
// the bow of the default hull that spread is ~0.3 m, which at Fn 0.08 is 125 radians of phase inside one
// section. `vPanels` subdivides every band uniformly to resolve it — see sizeFor().
function vEdges(
  vTop: number,
  vBot: number,
  wlGrade: number,
  vPanels: number,
): number[] {
  const knots: number[] = [];
  for (let k = Math.ceil(vTop + 1e-9); k <= Math.floor(vBot - 1e-9); k++)
    knots.push(k);
  const coarse = [vTop, ...knots, vBot];
  const e0 = coarse[1],
    out: number[] = [];
  // geometric grading of [vTop, e0]: widths h, 2h, 4h, … so the finest cell sits on the free surface
  const span = e0 - vTop,
    denom = Math.pow(2, wlGrade) - 1;
  let acc = vTop;
  for (let i = 0; i < wlGrade; i++) {
    out.push(acc);
    acc += (span * Math.pow(2, i)) / denom;
  }
  out.push(e0);
  for (let i = 2; i < coarse.length; i++) out.push(coarse[i]);
  if (vPanels <= 1) return out;
  // uniform refinement of every band, for the fan's own oscillation
  const fine: number[] = [];
  for (let i = 0; i < out.length - 1; i++)
    for (let s = 0; s < vPanels; s++)
      fine.push(out[i] + ((out[i + 1] - out[i]) * s) / vPanels);
  fine.push(out[out.length - 1]);
  return fine;
}

// A resolution-specific integration plan. All geometry classification, fallback selection, dry-column
// rejection and panel construction happen while compiling this object. The evaluator below receives only
// complete wet columns and positive section panels.
interface ColumnPlan {
  wu: number;
  fr: Frame;
  sec: Section;
  fr0: Frame;
  sec0: Section;
  fr1: Frame;
  sec1: Section;
  du: number;
  vPanels: [number, number][];
}

interface CenterplanePlan {
  columns: ColumnPlan[];
  spanFallbacks: number;
  sheerSubmerged: number;
}

function compileCenterplanePlan(
  model: Model,
  dom: WettedDomain,
  o: MichellOptions,
): CenterplanePlan {
  const { uA, uB } = dom;
  const uEdges: number[] = [uA];
  const segs = [uA, ...dom.breaks, uB],
    total = uB - uA;
  for (let s = 0; s < segs.length - 1; s++) {
    const a = segs[s],
      b = segs[s + 1],
      n = Math.max(1, Math.round((o.uPanels * (b - a)) / total));
    for (let i = 1; i <= n; i++) uEdges.push(a + ((b - a) * i) / n);
  }

  const gu = gaussLegendre(o.uNodes),
    columns: ColumnPlan[] = [];
  let spanFallbacks = 0,
    sheerSubmerged = 0;
  // The finite-difference scale used for ∂/∂u. It is clamped to the current panel below so it cannot cross a
  // station knot or a wetted-domain corner.
  const EU = 1e-4;

  for (let p = 0; p < uEdges.length - 1; p++) {
    const ua = uEdges[p],
      ub = uEdges[p + 1],
      hu = 0.5 * (ub - ua),
      mu = 0.5 * (ua + ub);
    for (let iu = 0; iu < o.uNodes; iu++) {
      const u = mu + hu * gu.x[iu],
        wu = hu * gu.w[iu],
        fr = frameAt(model, u),
        sec = sectionAt(model, u),
        got = spanAt(model, dom, fr, sec, u, o.scanV);
      if (got.fellBack) spanFallbacks++;
      if (!got.span) continue;
      const [vTop, vBot] = got.span;
      if (bindingAt(model, fr, sec, vTop) === BOUND.sheer) sheerSubmerged++;

      const eu = Math.min(EU, 0.2 * Math.min(u - ua, ub - u)),
        u0 = Math.max(0, u - eu),
        u1 = Math.min(1, u + eu),
        edges = vEdges(vTop, vBot, o.wlGrade, o.vPanels),
        vPanels: [number, number][] = [];
      for (let q = 0; q < edges.length - 1; q++)
        if (edges[q + 1] > edges[q]) vPanels.push([edges[q], edges[q + 1]]);

      columns.push({
        wu,
        fr,
        sec,
        fr0: frameAt(model, u0),
        sec0: sectionAt(model, u0),
        fr1: frameAt(model, u1),
        sec1: sectionAt(model, u1),
        du: u1 - u0,
        vPanels,
      });
    }
  }
  return { columns, spanFallbacks, sheerSubmerged };
}

// Walk the hull once and reduce it to the weighted node cloud. `scale` is metres per model unit — the ONE
// place the model's own units meet SI, because ν = g/U² is dimensional and a silent unit slip here is the
// failure mode of every Michell implementation.
//
// `domain` is an optimisation and nothing more: the sampler derives its own when none is given, and one built
// from a DIFFERENT model would produce nonsense, so pass it only where the model is demonstrably the same one
// (sampleForBandwidth's two passes are the case it exists for).
export function sampleCenterplane(
  model: Model,
  scale: number,
  options?: Partial<MichellOptions>,
  domain?: WettedDomain,
): Centerplane | null {
  const o = { ...DEFAULT_OPTIONS, ...options };
  const cr = Math.cos(model.deckRake),
    sr = Math.sin(model.deckRake);

  const dom = domain ?? wettedDomain(model, o.scanV);
  if (!dom) return null; // no wetted hull at all
  const { footU } = dom;

  // Compile every branch concerning the wetted geometry before entering the numerical evaluator: its columns
  // are all wet, its spans are resolved, and its section panels all have positive width.
  const plan = compileCenterplanePlan(model, dom, o);
  const gv = gaussLegendre(o.vNodes);
  const Xs: number[] = [],
    Zs: number[] = [],
    Ws: number[] = [];
  let volumeHalf = 0,
    areaProjected = 0,
    draft = 0,
    xAft = Infinity,
    xFwd = -Infinity,
    beamMax = 0,
    jacobianFlips = 0,
    fanMax = 0;

  for (const column of plan.columns) {
    const { wu, fr, sec, fr0, sec0, fr1, sec1, du } = column;
    for (const [va, vb] of column.vPanels) {
      const hv = 0.5 * (vb - va),
        mv = 0.5 * (va + vb);
      for (let iv = 0; iv < o.vNodes; iv++) {
        const v = mv + hv * gv.x[iv],
          wv = hv * gv.w[iv];
        const h = hydroAt(model, fr, sec, v, cr, sr);
        // ∂(X,Z)/∂v exactly, from the section curve's own tangent; only n is carried by the frame
        const [dn, dz] = sec.d(v),
          xv = dn * fr.n[0],
          zv = dz;
        const Xv = xv * cr - zv * sr,
          Zv = xv * sr + zv * cr;
        // ∂(X,Z)/∂u by central difference of the surface map at fixed v
        const a0 = hydroAt(model, fr0, sec0, v, cr, sr),
          a1 = hydroAt(model, fr1, sec1, v, cr, sr);
        const Xu = (a1.X - a0.X) / du,
          Zu = (a1.Z - a0.Z) / du;
        const J = Xu * Zv - Xv * Zu;
        if (J > 0) jacobianFlips++; // the hull's own orientation makes J < 0 (X grows with u, Z falls with v)
        const aJ = Math.abs(J) * wu * wv * scale * scale;
        const y = h.y * scale;
        Xs.push(h.X * scale);
        Zs.push(h.Z * scale);
        Ws.push(y * aJ);
        volumeHalf += y * aJ;
        areaProjected += aJ;
        if (-h.Z * scale > draft) draft = -h.Z * scale;
        if (h.X * scale < xAft) xAft = h.X * scale;
        if (h.X * scale > xFwd) xFwd = h.X * scale;
        if (2 * y > beamMax) beamMax = 2 * y;
        // the fan diagnostic: how far the true longitudinal coordinate sits from the station's own x
        const fan = Math.abs(h.X - fr.p[0] * cr) * scale;
        if (fan > fanMax) fanMax = fan;
      }
    }
  }
  if (!Xs.length) return null;
  const loa =
    model.sheerPlan[model.sheerPlan.length - 1].x - model.sheerPlan[0].x;
  return {
    X: Float64Array.from(Xs),
    Z: Float64Array.from(Zs),
    W: Float64Array.from(Ws),
    volumeHalf,
    areaProjected,
    draft,
    xAft,
    xFwd,
    beamMax,
    wettedLength: xFwd - xAft,
    columns: plan.columns.length,
    nodes: Xs.length,
    jacobianFlips,
    sheerSubmerged: plan.sheerSubmerged,
    fanMaxRatio: loa * scale > 0 ? fanMax / (loa * scale) : 0,
    fanSpread: fanMax,
    footU,
    spanFallbacks: plan.spanFallbacks,
  };
}

// ---------- 1b. sizing the sampling to the speed ----------
//
// This is the part it is easy to get wrong, and the failure is silent. The node cloud is θ-independent, which
// is what makes every speed cheap after the first — but the KERNEL is not. exp(i·ν·secθ·X) has wavelength
// 2π/(ν·secθ), and ν = g/U² blows up as speed falls: on a 3.9 m hull the kernel goes through 17 cycles along
// the hull at Fn 0.33 and 1068 at Fn 0.04. A grid that resolves the first does not resolve the second, and
// nothing in the arithmetic complains — it just returns a number built out of aliasing. On camber's default
// hull the baseline grid reports 6690 N at Fn 0.083 where the converged answer is 191 N.
//
// So the grid has to be sized from the bandwidth, in BOTH directions. Two oscillations to resolve:
//
//   • ALONG the hull: ν·secMax·L radians, resolved by the columns (uPanels × uNodes).
//   • ACROSS each section: ν·secMax·δX radians, where δX is the longitudinal spread the STATION FAN gives one
//     column. This one is easy to miss, and it is why the plan's Filon recommendation does not transfer here:
//     Filon's premise is that the inner section integral varies slowly along the hull, but camber's fanned
//     stations make that inner integral oscillatory in its own right — 125 radians across a single section at
//     Fn 0.083. Filon in the longitudinal direction would leave the section direction just as aliased.
//
// Plus the exponential's depth scale: exp(ν·sec²θ·Z) lives in a layer 1/(ν·sec²θ) thick, which the geometric
// grading has to reach down to.
//
// Calibrated on camber's default hull across Fn 0.10–1.0: 6 columns per longitudinal cycle holds R_w to a few
// tenths of a percent, and going to 12 moves it by less than that again.

export const NODES_PER_CYCLE = 6;

// The FLOOR for the angular cutoff. The cutoff itself is not a constant — see secMaxFor.
export const DEFAULT_SEC_MAX = 8;

// The angular cutoff has to follow the Froude number, because the truncation error does. Measured on camber's
// default hull, the resistance still lying past sec 8:
//
//     Fn      0.17    0.25    0.40    0.60    0.80    1.00
//     tail    0.5%    1.2%    2.2%    2.1%    3.4%    6.1%
//
// A flat sec 8 therefore understates R_w by six percent at the top of the useful range — not a rounding error,
// and not something a caller should have to discover. Raising it is nearly free exactly where it is needed
// (at Fn 1.0 the whole solve is 16 ms at sec 8 and 31 ms at sec 32) and ruinous exactly where it is not (at
// Fn 0.17, 168 ms becomes 10.4 s, because the sampling must resolve ν·secMax·L and ν is huge at low speed).
// So the cutoff rises with Fn. This rule holds the truncation under about 0.6% across Fn 0.1–1.0, which
// test/michell.ts checks against a sec-46 reference.
export const secMaxFor = (froude: number): number =>
  Math.min(32, Math.max(DEFAULT_SEC_MAX, 8 + 24 * (froude - 0.1)));

// tail ≈ TAIL_FROM_OCTAVE × (what the last octave of secθ contributed). Calibrated on the same sweep: the
// ratio sits between 0.16 and 0.41 over Fn 0.25–1.0 and cutoffs sec 8–32, with almost no dependence on Fn.
// The constant is deliberately set above the largest observed value — an estimator that guides a warning
// should err toward over-reporting, never under.
export const TAIL_FROM_OCTAVE = 0.45;

// The most nodes a sample will build. See sampleForBandwidth: this is a refusal threshold, not a target.
export const MAX_NODES = 260_000;

// The Froude range over which this is worth reporting at all, which is narrower than the range over which it
// will return a number. Both ends are physics, not numerics:
//
//   • BELOW ~0.10 the wave-making resistance is a negligible part of the total (viscous drag dominates
//     completely), while the kernel's wavelength — which goes as U² — collapses, so the cost of computing that
//     negligible number runs away. On camber's default hull Fn 0.04 asks for over a million nodes.
//   • ABOVE ~1.0 the boat is planing. Thin-ship theory is a displacement-speed model: it has no dynamic lift,
//     no sinkage, no trim, and the transom is long since ventilated. The θ integral also stops converging
//     inside a sensible cutoff, which waveResistance reports as a large tail.
//
// Outside this band, callers should say so rather than print a confident number.
export const USEFUL_FROUDE: [number, number] = [0.1, 1.0];
export const inUsefulRange = (froude: number): boolean =>
  froude >= USEFUL_FROUDE[0] && froude <= USEFUL_FROUDE[1];

export interface HullScales {
  wettedLength: number; // [m]
  draft: number; // [m]
  fanSpread: number; // [m], the within-column longitudinal spread
}

// The discretization that (ν, secMax) demands of a hull of these dimensions. Never returns less than `base`:
// the geometry floor still applies at high speed, where the kernel asks for almost nothing.
// Round up onto a coarse ladder (…, 96, 128, 192, 256, 384, …). The demand varies continuously with speed,
// but re-sampling the hull on every tick of a speed slider would make the tool unusable — quantizing means the
// sample is reused until a real threshold is crossed, at the price of at most 50% more nodes than needed.
function ladder(v: number, floor: number): number {
  let x = floor;
  while (x < v) x = x % 3 === 0 ? (x / 3) * 4 : x * 1.5;
  return Math.round(x);
}

export function sizeFor(
  dims: HullScales,
  nu: number,
  secMax: number,
  base: MichellOptions = DEFAULT_OPTIONS,
  perCycle = NODES_PER_CYCLE,
): MichellOptions {
  const k = nu * secMax; // the largest longitudinal wavenumber in play
  const longCycles = (k * dims.wettedLength) / (2 * Math.PI);
  const fanCycles = (k * dims.fanSpread) / (2 * Math.PI);
  // the section's bands: the graded ones plus roughly one per station knot. Only an estimate — vPanels
  // refines every band, so over-counting here costs a little and under-counting is what must be avoided.
  const bands = base.wlGrade + 3;
  return {
    ...base,
    uPanels: ladder(
      Math.ceil((perCycle * longCycles) / base.uNodes),
      base.uPanels,
    ),
    vPanels: ladder(
      Math.ceil((perCycle * fanCycles) / (base.vNodes * bands)),
      base.vPanels,
    ),
    // reach a depth scale of 1/(ν·sec²θ) with geometric grading: 2^grade cells across the top band
    wlGrade: Math.max(
      base.wlGrade,
      Math.min(
        16,
        Math.ceil(Math.log2(Math.max(2, dims.draft * nu * secMax * secMax))),
      ),
    ),
  };
}

export interface Resolution {
  perCycleLong: number; // columns per longitudinal wavelength at secMax
  perCycleFan: number; // section nodes per wavelength across one column's own X spread
  converged: boolean; // both meet the calibrated target
  nodes: number;
}

// What a cloud actually resolves at (ν, secMax). Report this rather than assuming: a cloud built for one speed
// and reused at a lower one is exactly the silent-aliasing case above.
export function resolutionOf(
  cp: Centerplane,
  nu: number,
  secMax: number,
  perCycle = NODES_PER_CYCLE,
): Resolution {
  const k = nu * secMax;
  const longCycles = (k * cp.wettedLength) / (2 * Math.PI);
  const fanCycles = (k * cp.fanSpread) / (2 * Math.PI);
  const perLong = longCycles > 0 ? cp.columns / longCycles : Infinity;
  const perNode = cp.columns > 0 ? cp.nodes / cp.columns : 0;
  const perFan = fanCycles > 0 ? perNode / fanCycles : Infinity;
  return {
    perCycleLong: perLong,
    perCycleFan: perFan,
    // a hair of tolerance: the ladder lands exactly on the target often enough that float noise would
    // otherwise report a grid built to spec as short of it
    converged: perLong >= perCycle * 0.995 && perFan >= perCycle * 0.995,
    nodes: cp.nodes,
  };
}

// Sample a hull at the resolution a given speed needs. Two passes: a cheap one to learn the hull's dimensions
// (they are what the sizing rule needs, and they are not known before sampling), then the real one. The probe
// is a few milliseconds against a sample that can be a second, and it is skipped when the baseline already
// suffices — which it does over most of the useful speed range.
//
// Both passes integrate over the SAME hull, so the domain is found once and shared. It is not exposed: a
// domain and a model that disagree would be a hard bug to see, and no caller outside this function has a
// reason to hold one.
export function sampleForBandwidth(
  model: Model,
  scale: number,
  nu: number,
  secMax: number,
  base: MichellOptions = DEFAULT_OPTIONS,
  maxNodes = MAX_NODES,
): { cp: Centerplane; resolution: Resolution; options: MichellOptions } | null {
  const dom = wettedDomain(model, base.scanV);
  if (!dom) return null;
  const probe = sampleCenterplane(model, scale, base, dom);
  if (!probe) return null;
  const want = sizeFor(probe, nu, secMax, base);
  // The cost ceiling. Below about Fn 0.1 the demand runs away — the kernel's wavelength goes as U², so on a
  // 3.9 m hull Fn 0.04 asks for 1.5 million nodes — and an interactive tool cannot honour that. Rather than
  // freeze, cap the grid and return `converged: false`, which is the caller's cue to say the number is not
  // trustworthy instead of printing it as though it were.
  const perColumn =
    probe.nodes / Math.max(1, probe.columns * probe.nodes ? 1 : 1);
  const nodesPerColumn = probe.nodes / Math.max(1, probe.columns);
  void perColumn;
  let capped = want;
  const cost = (o: MichellOptions): number =>
    o.uPanels * o.uNodes * nodesPerColumn * o.vPanels;
  if (cost(want) > maxNodes) {
    // give up the section refinement first — the longitudinal axis is the faster oscillation of the two, and
    // starving it is what produced the aliased answers in the first place
    const shrunkV = {
      ...want,
      vPanels: Math.max(
        base.vPanels,
        Math.floor(want.vPanels / Math.sqrt(cost(want) / maxNodes)),
      ),
    };
    capped =
      cost(shrunkV) > maxNodes
        ? {
            ...shrunkV,
            uPanels: Math.max(
              base.uPanels,
              Math.floor((shrunkV.uPanels * maxNodes) / cost(shrunkV)),
            ),
          }
        : shrunkV;
  }
  const same =
    capped.uPanels === base.uPanels &&
    capped.vPanels === base.vPanels &&
    capped.wlGrade === base.wlGrade;
  const cp = same ? probe : sampleCenterplane(model, scale, capped, dom);
  if (!cp) return null;
  return { cp, resolution: resolutionOf(cp, nu, secMax), options: capped };
}

// ---------- 2. the free-wave spectrum ----------

// F(θ) for a whole θ grid, in one pass per angle over the node cloud.
//
//     F = −i·ν·secθ · Σ W·exp(ν·sec²θ·Z)·exp(i·ν·secθ·X)
//
// b = i·ν·secθ is purely imaginary WHATEVER the rake — the rake is already inside X and Z — so a node costs
// one real exp and one sin/cos, never a complex exponential. Writing S = Sr + i·Si for the sum, F = ν·secθ·(Si
// − i·Sr). Returned as two arrays rather than objects: this is the hot loop of everything downstream.
export function spectrum(
  cp: Centerplane,
  nu: number,
  thetas: Float64Array | number[],
): { re: Float64Array; im: Float64Array } {
  const n = thetas.length,
    re = new Float64Array(n),
    im = new Float64Array(n),
    { X, Z, W } = cp,
    N = X.length;
  for (let t = 0; t < n; t++) {
    const sec = 1 / Math.cos(thetas[t]),
      a = nu * sec * sec,
      b = nu * sec;
    let sr = 0,
      si = 0;
    for (let i = 0; i < N; i++) {
      const e = W[i] * Math.exp(a * Z[i]),
        ph = b * X[i];
      sr += e * Math.cos(ph);
      si += e * Math.sin(ph);
    }
    re[t] = b * si;
    im[t] = -b * sr;
  }
  return { re, im };
}

// ---------- 3. wave resistance ----------

export interface Conditions {
  U: number; // speed through the water [m/s]
  rho: number; // density [kg/m³]
}

export interface ThetaGrid {
  theta: Float64Array;
  weight: Float64Array; // quadrature weights over [0, thetaMax]
  thetaMax: number;
}

// Where to stop the θ integral. The tail of sec³θ·|F|² behaves like cosθ for a hull with a wetted transom (the
// transom source line contributes |F|² ~ λ⁻⁴), so the truncated remainder is ~cos²θmax/2 relative — 85° leaves
// under half a percent, and the cutoff is a refinement control like any other (see convergence() below).
export function thetaCutoff(secMax = DEFAULT_SEC_MAX): number {
  return Math.acos(1 / secMax);
}

// A θ grid graded for the integrand's own oscillation. F(θ) carries phase ~ν·secθ·x, so successive panels are
// sized to a fixed increment of ν·L·secθ rather than of θ: uniform-in-θ panels are wastefully fine near 0 and
// hopelessly coarse near the cutoff, where secθ runs away.
export function thetaGrid(
  nu: number,
  L: number,
  thetaMax: number,
  dPhase = 2.0,
  nodes = 6,
  maxPanels = 4000,
): ThetaGrid {
  const edges: number[] = [0];
  const secMax = 1 / Math.cos(thetaMax);
  let s = 1;
  while (edges[edges.length - 1] < thetaMax && edges.length < maxPanels) {
    const step = Math.max(dPhase / Math.max(nu * L, 1e-9), 0.02);
    s = Math.min(s + step, secMax);
    const th = Math.min(Math.acos(1 / s), thetaMax);
    if (th <= edges[edges.length - 1] + 1e-12) break;
    edges.push(th);
  }
  if (edges[edges.length - 1] < thetaMax) edges.push(thetaMax);
  const g = gaussLegendre(nodes),
    m = (edges.length - 1) * nodes;
  const theta = new Float64Array(m),
    weight = new Float64Array(m);
  let k = 0;
  for (let i = 0; i < edges.length - 1; i++) {
    const h = 0.5 * (edges[i + 1] - edges[i]),
      c = 0.5 * (edges[i] + edges[i + 1]);
    for (let j = 0; j < nodes; j++, k++) {
      theta[k] = c + h * g.x[j];
      weight[k] = h * g.w[j];
    }
  }
  return { theta, weight, thetaMax };
}

export interface WaveResult {
  rw: number; // wave-making resistance [N]
  cw: number; // R_w / (½ρU²·L²) — a shape coefficient on the wetted length
  froude: number;
  nu: number; // g/U² [1/m]
  grid: ThetaGrid;
  re: Float64Array; // F(θ) on the grid
  im: Float64Array;
  density: Float64Array; // dR_w/dθ, whose integral is rw
  tail: number; // estimated fraction of R_w beyond thetaMax
}

// `spec` lets a caller hand back a spectrum it has already evaluated on the SAME grid — the pass over the node
// cloud is the expensive part, and at the slow end of the range it is seconds, so computing it twice for the
// same angles is not a rounding error.
export function waveResistance(
  cp: Centerplane,
  cond: Conditions,
  grid?: ThetaGrid,
  dPhase = 2.0,
  spec?: { re: Float64Array; im: Float64Array },
): WaveResult {
  const nu = G / (cond.U * cond.U),
    L = cp.wettedLength;
  const g =
    grid ??
    thetaGrid(nu, L, thetaCutoff(secMaxFor(cond.U / Math.sqrt(G * L))), dPhase);
  const { re, im } =
    spec && spec.re.length === g.theta.length
      ? spec
      : spectrum(cp, nu, g.theta);
  const k = (4 * cond.rho * G * G) / (Math.PI * cond.U * cond.U);
  const density = new Float64Array(g.theta.length);
  let rw = 0;
  for (let i = 0; i < g.theta.length; i++) {
    const sec = 1 / Math.cos(g.theta[i]),
      d = k * sec * sec * sec * (re[i] * re[i] + im[i] * im[i]);
    density[i] = d;
    rw += d * g.weight[i];
  }
  // Tail estimate. The old version read the single last sample and assumed a cosθ decay, which understated the
  // truncation badly whenever the integrand had not started decaying by the cutoff — it reported 0.01% at
  // Fn 1.66, where a third of R_w actually lies past sec 8. Instead fit a power law dR/dθ ∝ sec^p over the
  // last stretch of the grid and integrate the fit out to π/2, which reports growth as growth.
  // The tail past the cutoff, MEASURED rather than extrapolated.
  //
  // The previous version fitted a power law through two samples of the density and integrated it to π/2. That
  // is not reliable: dR/dθ oscillates, so two points pick up whatever phase they happen to land on, and it
  // failed in both directions — it claimed 100% at Fn 0.33 and 0.38% at Fn 1.0 where the truth was 6.1%.
  //
  // Instead read the contribution of the LAST OCTAVE of secθ, which integrates over the oscillation instead of
  // sampling it, and scale it by a calibrated constant. See TAIL_FROM_OCTAVE.
  let octave = 0;
  {
    // θ at half the cutoff's secθ — the start of the final octave
    const half = Math.acos(Math.min(1, 2 * Math.cos(g.thetaMax)));
    for (let i = 0; i < g.theta.length; i++)
      if (g.theta[i] >= half) octave += density[i] * g.weight[i];
  }
  const tailRw = TAIL_FROM_OCTAVE * octave;
  return {
    rw,
    cw: rw / (0.5 * cond.rho * cond.U * cond.U * L * L),
    froude: cond.U / Math.sqrt(G * L),
    nu,
    grid: g,
    re,
    im,
    density,
    // clamped: past the cutoff the fitted law is an extrapolation, and "more outside than inside" is all
    // the caller can act on — a precise number there would be false precision
    tail: rw > 0 ? Math.min(1, tailRw / rw) : 0,
  };
}

// ---------- 3b. fleets: exact wave interference ----------
//
// Thin-ship amplitudes SUPERPOSE. A hull placed at (dx, dy) contributes its own F times a placement phase —
// exp(i·ν·secθ·dx) longitudinally and exp(i·ν·sec²θ·sinθ·dy) transversely — so the fleet's resistance uses
// |Σ_j F_j·e^{iφ_j}|². The interference is exact within the theory, and nothing about a hull is recomputed
// when it moves: only φ_j changes. That is what makes dragging a demihull around interactive.
//
// The transverse phase is ODD in θ, so unlike a single hull an off-centre arrangement is not symmetric between
// the two Kelvin half-systems. Both are carried explicitly; a fleet on the centreline collapses back to the
// single-hull formula exactly. For a symmetric pair at ±s/2 this reproduces the classical 4cos²(½·k_t·s).
export interface FleetMember {
  cp: Centerplane;
  at: Placement;
}

export interface FleetResult {
  rw: number; // combined wave resistance [N]
  standalone: number[]; // each member's R_w on its own [N]
  interference: number; // combined / Σ standalone — below 1 means the hulls cancel each other's waves
  nu: number;
  froude: number;
  grid: ThetaGrid;
  parts: { re: Float64Array; im: Float64Array; at: Placement }[];
  density: Float64Array; // dR_w/dθ for the fleet
}

export function fleetResistance(
  members: FleetMember[],
  cond: Conditions,
  grid?: ThetaGrid,
  dPhase = 2.0,
): FleetResult {
  const nu = G / (cond.U * cond.U);
  const L = Math.max(...members.map((m) => m.cp.wettedLength));
  const reach =
    L +
    Math.max(0, ...members.map((m) => Math.abs(m.at.dx) + Math.abs(m.at.dy)));
  const g =
    grid ??
    thetaGrid(
      nu,
      reach,
      thetaCutoff(secMaxFor(cond.U / Math.sqrt(G * L))),
      dPhase,
    );
  const parts = members.map((m) => ({
    ...spectrum(m.cp, nu, g.theta),
    at: m.at,
  }));
  const k = (2 * cond.rho * G * G) / (Math.PI * cond.U * cond.U);
  const density = new Float64Array(g.theta.length);
  let rw = 0;
  for (let i = 0; i < g.theta.length; i++) {
    const sec = 1 / Math.cos(g.theta[i]),
      beta = nu * sec,
      kt = nu * sec * sec * Math.sin(g.theta[i]);
    let pr = 0,
      pi = 0,
      mr = 0,
      mi = 0; // the +θ and −θ half-systems
    for (const p of parts) {
      const a = beta * p.at.dx,
        b = kt * p.at.dy;
      const cp2 = Math.cos(a + b),
        sp2 = Math.sin(a + b),
        cm = Math.cos(a - b),
        sm = Math.sin(a - b);
      pr += p.re[i] * cp2 - p.im[i] * sp2;
      pi += p.re[i] * sp2 + p.im[i] * cp2;
      mr += p.re[i] * cm - p.im[i] * sm;
      mi += p.re[i] * sm + p.im[i] * cm;
    }
    const d = k * sec * sec * sec * (pr * pr + pi * pi + mr * mr + mi * mi);
    density[i] = d;
    rw += d * g.weight[i];
  }
  // each member on its own, at the same θ grid, so the interference factor is a like-for-like ratio
  const standalone = parts.map((p) => {
    let s = 0;
    for (let i = 0; i < g.theta.length; i++) {
      const sec = 1 / Math.cos(g.theta[i]);
      s +=
        2 *
        k *
        sec *
        sec *
        sec *
        (p.re[i] * p.re[i] + p.im[i] * p.im[i]) *
        g.weight[i];
    }
    return s;
  });
  const sum = standalone.reduce((a, b) => a + b, 0);
  return {
    rw,
    standalone,
    interference: sum > 0 ? rw / sum : 1,
    nu,
    froude: cond.U / Math.sqrt(G * L),
    grid: g,
    parts,
    density,
  };
}

// ---------- 4. the far-field wave pattern ----------
//
// The elevation is a superposition over the same spectrum, with the Kelvin dispersion k(θ) = ν·sec²θ:
//
//     ζ(X, Y) = Re ∫_{−π/2}^{π/2} A(θ)·exp[i·ν·secθ·(X + Y·tanθ)] dθ ,   A(θ) = −(2ν/π)·sec³θ·conj(F(θ))
//
// The weight is not free to choose: it is pinned by the deep-water free-wave energy identity
// R_w = ½πρU²∫|A|²cos³θ dθ, which substituting A reproduces (4ρg²/πU²)∫sec³θ|F|²dθ — the resistance formula in
// §3, exactly. So the two outputs of this file share one normalization by construction, not by fitting.
//
// F is even in θ (secθ is), and tanθ is odd, so the ±θ halves of the range fold together. For a hull placed
// at (dx, dy) that leaves
//
//     ζ(X, Y) = Σ_t 2·w_t·Re[A(θ_t)·e^{i·ν·secθ·(X−dx)}] · cos(ν·sec²θ·sinθ·(Y−dy))
//
// — SEPARABLE in X and Y. So a whole grid is one outer product per angle instead of a transcendental per
// (pixel, angle), and a fleet is the sum of its members' separable fields. That separability is also why
// dragging a hull around the fleet view is free: only dx and dy move, never F.
//
// Validity: this is the FREE-WAVE part of the linear solution. It is physical astern of the hull, not on it
// and not ahead of it, and it carries no local (non-wavelike) disturbance.

export interface FieldGrid {
  x0: number; // X of column 0 [m]
  dx: number;
  nx: number;
  y0: number; // Y of row 0 [m]
  dy: number;
  ny: number;
}

export interface FieldResult {
  z: Float64Array; // elevation [m], row-major, ny rows of nx
  max: number; // max |ζ|
  bandLimited: boolean; // true if the grid was too coarse for the shortest diverging waves and θ was tapered
}

// One hull's placement in a fleet: a rigid translation of its centreplane. Thin-ship amplitudes superpose, so
// a hull at (dx, dy) contributes its own F times a placement phase — which is why dragging hulls around in the
// fleet view is free: nothing is recomputed, the fields are translated and summed.
export interface Placement {
  dx: number; // [m] along the track, + forward
  dy: number; // [m] to starboard
}

// ζ on a grid, from one or more placed spectra sharing a θ grid. `parts` are the per-hull F(θ) arrays.
export function waveField(
  parts: { re: Float64Array; im: Float64Array; at: Placement }[],
  grid: ThetaGrid,
  nu: number,
  fg: FieldGrid,
): FieldResult {
  const nt = grid.theta.length;
  // Band limit: an angle whose waves are shorter than a few grid cells cannot be drawn, only aliased. Fade
  // those out with a raised cosine rather than cutting them, so the truncation does not ring across the whole
  // field. 2π/k(θ) = 2π·cos²θ/ν is the wavelength along the propagation direction, and it collapses as θ → π/2
  // — the short diverging waves are always the first to go.
  // an axis sampled at a single point imposes no resolution limit of its own — a longitudinal wave cut must
  // not have its diverging waves suppressed by a transverse step it never takes
  const cell = Math.max(
      fg.nx > 1 ? Math.abs(fg.dx) : 0,
      fg.ny > 1 ? Math.abs(fg.dy) : 0,
    ),
    lamMin = 3 * cell,
    lamFade = 6 * cell;
  let bandLimited = false;

  // per angle: the taper, the longitudinal wavenumber β, and the transverse one k_t
  const taper = new Float64Array(nt),
    beta = new Float64Array(nt),
    kt = new Float64Array(nt);
  for (let t = 0; t < nt; t++) {
    const sec = 1 / Math.cos(grid.theta[t]),
      lam = (2 * Math.PI) / (nu * sec * sec);
    beta[t] = nu * sec;
    kt[t] = nu * sec * sec * Math.sin(grid.theta[t]);
    taper[t] =
      lam >= lamFade
        ? 1
        : lam <= lamMin
          ? 0
          : 0.5 -
            0.5 * Math.cos((Math.PI * (lam - lamMin)) / (lamFade - lamMin));
    if (taper[t] < 1) bandLimited = true;
  }

  const z = new Float64Array(fg.nx * fg.ny),
    P = new Float64Array(nt * fg.nx),
    C = new Float64Array(nt * fg.ny);
  // Each hull's field is built and accumulated separately: its placement enters as a shift of X and Y, which
  // keeps the ±θ fold (and therefore the separability) valid for any arrangement, symmetric or not.
  for (const p of parts) {
    for (let t = 0; t < nt; t++) {
      // an angle the grid cannot carry contributes nothing — skip it before building its tables
      if (taper[t] === 0) {
        P.fill(0, t * fg.nx, (t + 1) * fg.nx);
        C.fill(0, t * fg.ny, (t + 1) * fg.ny);
        continue;
      }
      const sec = 1 / Math.cos(grid.theta[t]);
      // A(θ) = −(2ν/π)·sec³θ·conj(F), times the quadrature weight, the taper, and the fold's factor of 2
      const g =
          (-2 * nu * sec * sec * sec * grid.weight[t] * taper[t] * 2) / Math.PI,
        Ar = g * p.re[t],
        Ai = -g * p.im[t];
      for (let i = 0; i < fg.nx; i++) {
        const ph = beta[t] * (fg.x0 + i * fg.dx - p.at.dx);
        P[t * fg.nx + i] = Ar * Math.cos(ph) - Ai * Math.sin(ph);
      }
      for (let j = 0; j < fg.ny; j++)
        C[t * fg.ny + j] = Math.cos(kt[t] * (fg.y0 + j * fg.dy - p.at.dy));
    }
    // the outer product, accumulated: one multiply-add per (angle, pixel), no transcendentals left
    for (let j = 0; j < fg.ny; j++) {
      const row = j * fg.nx;
      for (let t = 0; t < nt; t++) {
        const c = C[t * fg.ny + j];
        if (c === 0) continue;
        const off = t * fg.nx;
        for (let i = 0; i < fg.nx; i++) z[row + i] += P[off + i] * c;
      }
    }
  }
  let max = 0;
  for (let i = 0; i < z.length; i++) max = Math.max(max, Math.abs(z[i]));
  return { z, max, bandLimited };
}

// ---------- 5. what this does not model ----------
//
// • Wave-making only. No viscous or form drag: R_w is a shape diagnostic, not a resistance prediction.
// • The free-wave field only — no local non-wavelike disturbance, so the pattern is meaningless within about
//   a wavelength of the hull, and it does not vanish upstream on its own. Restrict the domain; don't trust it
//   ahead of the bow.
// • Thin-ship linearisation: the error grows with beam/length, in a direction that depends on the hull and the
//   Froude number. Compare against benchmarks before believing an absolute number.
// • A wetted transom is carried as the concentrated source line the theory gives it. Real transoms ventilate
//   above a critical speed and stop behaving like that; a virtual stern extension is the usual modelling
//   answer and is not implemented here.
// • No sinkage or trim — model.deckRake is whatever it is set to, not an equilibrium. No planing.
